# Business Goal/Outcome

## Goal
Give a realtor like Jeanine a data-backed answer to the question every seller asks ("What's my home worth, and how long will it take?") and every buyer asks ("Do I have room to negotiate?"), specific to the zip they're standing in.

## Outcomes
- Realtor can price the seller correctly in listing appts 
- Aide buyer consolutations and negotiation strategy
- Help with prospecting and knowing which zips to farm
- Data to feed market update content
- Help relay market expertise

# Research Question
Where in Orlando have sellers lost leverage since 2023, and where do they still have it?

# Hypothesis

**H1: New construction hurt resale sellers most.**  
		In 34787 and 32712, price cut share and days on market will have risen more than the metro average since 2022, because builders' incentives pull buyers away from resale homes.  
		_Rejected if:_ both zips' increases are at or below the metro average.


**H2: Windermere held up.**  
		In 34786, the leverage score will have dropped less than the metro average since 2022, because scarce lakefront and large-lot homes and less rate-sensitive buyers protect sellers.  
		_Rejected if:_ 34786's drop is at or above the metro average. If that happens, the Horizon West portion of the zip may be dragging it down.


**H3: Affordable zips**
 34761 and 32703 will have lost less leverage than 34787 and 32712, because they have less new-construction competition. _Rejected if:_ their drop is the same as or larger than the growth zips'.

In [15]:
import pandas as pd

In [16]:
historical = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip_History.csv')
historical

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,74003,"bartlesville, ok",150000.0,0.0000,0.0714,45,-0.0722,0.0714,70.0,...,208058.0,-0.0086,0.0436,71,-0.0596,0.1639,0.5778,0.0417,0.1254,0.0
1,202608,61353,"paw paw, il",294450.0,0.0865,0.0711,7,0.2727,0.4000,27.0,...,432643.0,0.2654,0.2023,8,0.3333,0.1429,0.2143,0.0325,-0.3857,1.0
2,202608,35765,"pisgah, al",307950.0,0.0448,0.1322,15,0.0345,0.5000,105.0,...,312969.0,-0.0256,-0.1669,18,0.1613,0.3846,0.1333,0.0644,-0.0667,1.0
3,202608,21664,"secretary, md",349900.0,0.0294,0.0218,2,0.3333,-0.5000,54.0,...,349900.0,0.0294,0.1915,2,-0.3333,-0.5000,0.0000,-0.6667,-0.2500,0.0
4,202608,37221,"nashville, tn",519900.0,-0.0295,-0.0877,235,0.0129,0.0930,64.0,...,742763.0,0.0067,0.0582,312,-0.0473,-0.0064,0.3277,-0.0861,-0.1375,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3452028,201607,8828,"helmetta, nj",218000.0,NaN,NaN,22,NaN,NaN,67.0,...,243027.0,NaN,NaN,22,NaN,NaN,0.0455,NaN,NaN,NaN
3452029,201607,30536,"ellijay, ga",249350.0,NaN,NaN,128,NaN,NaN,86.0,...,309281.0,NaN,NaN,128,NaN,NaN,0.0118,NaN,NaN,NaN
3452030,201607,37863,"pigeon forge, tn",224750.0,NaN,NaN,189,NaN,NaN,115.0,...,283587.0,NaN,NaN,226,NaN,NaN,0.2042,NaN,NaN,NaN
3452031,201607,32097,"yulee, fl",231973.0,NaN,NaN,150,NaN,NaN,69.0,...,324656.0,NaN,NaN,252,NaN,NaN,0.6923,NaN,NaN,NaN
3452032,201607,59064,"pompeys pillar, mt",199500.0,NaN,NaN,1,NaN,NaN,14.0,...,199500.0,NaN,NaN,1,NaN,NaN,1.0000,NaN,NaN,NaN

In [27]:
august = pd.read_csv('/Users/medhasubramaniyan/Desktop/GitHub_Repos/orlando-seller-leverage-analysis/data/RDC_Inventory_Core_Metrics_Zip.csv')
august

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202608,78956,"schulenburg, tx",314000.0,-0.1253,0.0502,28,0.1200,0.4000,124.0,...,410433.0,-0.0986,0.2020,32,0.1228,0.3913,0.1786,0.0386,-0.0214,1
1,202608,30535,"demorest, ga",415000.0,-0.0259,0.0038,55,-0.0090,0.4865,90.0,...,461853.0,-0.0132,0.0613,68,-0.0933,0.4167,0.2545,-0.0878,-0.0428,1
2,202608,83316,"buhl, id",510000.0,0.0000,0.2146,45,-0.0110,-0.0816,79.0,...,699305.0,-0.0023,0.2881,55,-0.0833,-0.1129,0.2222,-0.1184,-0.0635,0
3,202608,94806,"san pablo, ca",577500.0,0.0226,-0.0077,71,0.2034,-0.1013,38.0,...,574916.0,0.0050,-0.0158,91,0.0581,-0.1947,0.3099,-0.1732,-0.1205,0
4,202608,37820,"new market, tn",735000.0,0.0426,0.4703,23,0.1500,0.0455,57.0,...,771742.0,-0.0668,0.5105,29,0.1154,-0.1714,0.3043,-0.0207,-0.1957,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29046,202608,50546,"havelock, ia",265500.0,0.0000,0.0215,1,0.0000,0.0000,81.0,...,265500.0,0.0000,0.0215,2,1.0000,0.0000,1.0000,NaN,0.0000,0
29047,202608,54530,"hawkins, wi",297500.0,0.0000,2.1349,3,-0.1429,0.5000,59.0,...,244967.0,-0.0126,1.5813,4,0.1429,0.3333,0.6667,NaN,0.1667,1
29048,202608,35755,"langston, al",574500.0,0.1011,-0.2584,12,0.0000,1.0000,115.0,...,725423.0,0.0650,-0.3124,14,0.1667,1.0000,0.0833,NaN,-0.0833,1
29049,202608,69148,"lisco, ne",98700.0,0.0000,-0.7005,1,0.0000,0.0000,107.0,...,98700.0,0.0000,-0.7005,1,0.0000,0.0000,1.0000,NaN,NaN,1
29050,202608,95459,"manchester, ca",1206250.0,-0.1904,0.5366,12,0.0909,0.2000,148.0,...,2114242.0,-0.0613,0.0235,12,0.0909,0.0909,0.0833,NaN,-0.0167,1

### Filtering national zip level data down to Orlando, Florida

In [48]:
# the only way we can filter to Orlando, Florida is by spltting zip_name into city, state

#
orl = august.copy()
orl[['city', 'state']] = orl['zip_name'].str.split(',', expand=True)
orl['state'] = orl['state'].str.strip()
orl['city'] = orl['city'].str.strip()

In [ ]:
orl = orl[orl['state'] == 'fl']
orl['state'].nunique() #we've filtered down to florida! (only 1 unique)
orl['city'].nunique() #interesting, there are 418 municipalities in florida

418

In [56]:
orl.info()

<class 'pandas.core.frame.DataFrame'>
Index: 933 entries, 53 to 28942
Data columns (total 48 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   month_date_yyyymm                        933 non-null    int64
 1   postal_code                              933 non-null    int64
 2   zip_name                                 933 non-null    object
 3   median_listing_price                     933 non-null    float64
 4   median_listing_price_mm                  931 non-null    float64
 5   median_listing_price_yy                  927 non-null    float64
 6   active_listing_count                     933 non-null    int64
 7   active_listing_count_mm                  930 non-null    float64
 8   active_listing_count_yy                  927 non-null    float64
 9   median_days_on_market                    933 non-null    float64
 10  median_days_on_market_mm                 931 non-null    float64
 11  median_days_on_market_yy                 926 non-null    float64
 12  new_listing_count                        933 non-null    int64
 13  new_listing_count_mm                     873 non-null    float64
 14  new_listing_count_yy                     839 non-null    float64
 15  price_increased_count                    933 non-null    int64
 16  price_increased_count_mm                 342 non-null    float64
 17  price_increased_count_yy                 255 non-null    float64
 18  price_increased_share                    933 non-null    float64
 19  price_increased_share_mm                 932 non-null    float64
 20  price_increased_share_yy                 927 non-null    float64
 21  price_reduced_count                      933 non-null    float64
 22  price_reduced_count_mm                   869 non-null    float64
 23  price_reduced_count_yy                   849 non-null    float64
 24  price_reduced_share                      933 non-null    float64
 25  price_reduced_share_mm                   932 non-null    float64
 26  price_reduced_share_yy                   927 non-null    float64
 27  pending_listing_count                    916 non-null    float64
 28  pending_listing_count_mm                 909 non-null    float64
 29  pending_listing_count_yy                 904 non-null    float64
 30  median_listing_price_per_square_foot     933 non-null    float64
 31  median_listing_price_per_square_foot_mm  931 non-null    float64
 32  median_listing_price_per_square_foot_yy  926 non-null    float64
 33  median_square_feet                       933 non-null    float64
 34  median_square_feet_mm                    931 non-null    float64
 35  median_square_feet_yy                    926 non-null    float64
 36  average_listing_price                    933 non-null    float64
 37  average_listing_price_mm                 931 non-null    float64
 38  average_listing_price_yy                 927 non-null    float64
 39  total_listing_count                      933 non-null    int64
 40  total_listing_count_mm                   932 non-null    float64
 41  total_listing_count_yy                   927 non-null    float64
 42  pending_ratio                            916 non-null    float64
 43  pending_ratio_mm                         907 non-null    float64
 44  pending_ratio_yy                         905 non-null    float64
 45  quality_flag                             933 non-null    int64
 46  city                                     933 non-null    object
 47  state                                    933 non-null    object
dtypes: float64(38), int64(7), object(3)
memory usage: 357.2+ KB

In [ ]:
# jeanines focus: 34786 (windermere), 34787 (winter garden), 34761 (ocoee), apopka north (32712), apopka (32703), DTO (32801) 
focus_zips = [34786, 34787, 34761, 32712 , 32703, 32801]
orl[orl['postal_code'].isin(focus_zips)]

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state
5792,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,...,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0,ocoee,fl
16047,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,...,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0,apopka,fl
20629,202608,34786,"windermere, fl",1089000.0,-0.0200,0.1204,233,-0.0251,-0.0567,75.0,...,0.3265,310,-0.0143,-0.0520,0.3391,0.0127,0.0030,0,windermere,fl
22377,202608,32703,"apopka, fl",405000.0,0.0095,0.0387,169,0.0563,-0.0398,66.0,...,0.0266,263,-0.0573,-0.0993,0.5740,-0.1604,-0.0681,0,apopka,fl
22613,202608,32801,"orlando, fl",338000.0,-0.0721,0.0090,126,-0.0156,-0.1923,101.0,...,-0.0163,144,0.0141,-0.1628,0.1349,0.0255,0.0195,0,orlando,fl
24400,202608,34787,"winter garden, fl",590000.0,0.0022,-0.0407,639,-0.0244,-0.0169,72.0,...,-0.0506,960,-0.0264,0.1622,0.5102,0.0048,0.2286,0,winter garden,fl

In [74]:
# greater central forida zips 
orlando_orange_county = [
    "32801", "32803", "32804", "32805", "32806", "32808", "32810",
    "32807", "32817", "32826", "32819", "32828", "32827", "32832", 
    "32835", "32703", "32704", "32712", "34761", "34787", "34786"
]
orlando_orange_county = list(map(int, orlando_orange_county))

seminole_county = [
    "32701", "32714", "32750", "32779", "32746", "32771", 
    "32772", "32773", "32707", "32708", "32765", "32766"
]
seminole_county = list(map(int, seminole_county))

osceola_county = [
    "34741", "34743", "34744", "34746", "34747", "34758",
    "34769", "34770", "34771", "34772"
]
osceola_county = list(map(int, osceola_county))

central_fl_tri_county = orlando_orange_county + seminole_county + osceola_county


central_fl = orl[orl['postal_code'].isin(central_fl_tri_county)]
orl = orl[orl['postal_code'].isin(orlando_orange_county)]

In [73]:
central_fl

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state
1178,202608,32773,"sanford, fl",324900.0,0.0116,-0.0899,104,-0.0370,-0.0095,66.0,...,-0.0887,153,0.0000,0.0200,0.4712,0.0313,0.0426,0,sanford,fl
2094,202608,32807,"orlando, fl",350000.0,0.0051,-0.0141,81,0.0452,0.1096,62.0,...,0.0233,123,0.0250,0.1942,0.5185,-0.0234,0.0939,0,orlando,fl
3183,202608,32779,"longwood, fl",509000.0,-0.0414,0.0283,113,0.0135,-0.0661,61.0,...,0.2629,157,-0.0819,-0.0126,0.4159,-0.1177,0.0854,0,longwood,fl
4683,202608,32714,"altamonte springs, fl",210000.0,-0.0455,-0.1495,172,0.1205,0.1026,61.0,...,-0.1118,212,0.0600,0.0653,0.2326,-0.0704,-0.0431,1,altamonte springs,fl
4969,202608,32707,"casselberry, fl",342450.0,0.0149,-0.1127,89,0.0988,-0.2328,50.0,...,-0.0153,134,0.0677,-0.1779,0.5056,-0.0376,0.1177,1,casselberry,fl
4978,202608,34772,"saint cloud, fl",434990.0,0.0297,-0.0114,314,0.0228,0.1460,67.0,...,0.0019,443,0.0485,0.2730,0.4013,0.0169,0.1239,0,saint cloud,fl
5792,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,...,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0,ocoee,fl
6641,202608,32819,"orlando, fl",525000.0,-0.0223,-0.0278,198,-0.0025,-0.1646,87.0,...,0.0056,235,-0.0208,-0.1840,0.1869,-0.0197,-0.0072,0,orlando,fl
6850,202608,32765,"oviedo, fl",499900.0,-0.0326,0.0099,163,-0.0298,-0.1044,58.0,...,-0.0264,236,-0.0503,-0.0745,0.4724,-0.0306,0.0823,0,oviedo,fl
7574,202608,32817,"orlando, fl",417500.0,-0.0430,-0.1278,53,-0.0702,-0.2090,50.0,...,-0.2889,78,-0.1086,-0.2041,0.4717,-0.1072,0.0090,1,orlando,fl
9215,202608,32806,"orlando, fl",485000.0,-0.0472,-0.0241,130,0.0788,-0.0370,72.0,...,0.0463,170,0.0366,-0.0230,0.3077,-0.0616,0.0114,0,orlando,fl
11456,202608,32746,"lake mary, fl",440000.0,-0.0110,0.0023,158,0.0569,-0.1640,64.0,...,-0.0943,224,0.0067,-0.1146,0.4241,-0.0442,0.1013,0,lake mary,fl
12414,202608,34744,"kissimmee, fl",415000.0,-0.0183,-0.0349,298,0.0420,0.1462,76.0,...,-0.0600,375,0.0638,0.0714,0.2718,0.0253,-0.0859,0,kissimmee,fl
13430,202608,32827,"orlando, fl",849945.0,0.0011,0.1691,185,-0.0750,0.1212,82.0,...,0.2297,243,-0.0654,0.1302,0.3135,0.0135,0.0287,0,orlando,fl
13578,202608,32750,"longwood, fl",429900.0,-0.0082,-0.0037,55,0.0476,-0.3210,65.0,...,-0.0193,78,-0.0983,-0.3097,0.3636,-0.2840,-0.0191,0,longwood,fl
14749,202608,32826,"orlando, fl",212000.0,-0.3737,-0.4308,64,0.1743,0.3913,42.0,...,-0.3014,89,0.0788,0.4833,0.3906,-0.1231,0.0645,1,orlando,fl
16000,202608,32832,"orlando, fl",529990.0,-0.0227,-0.0184,221,0.0208,-0.0515,72.0,...,0.0176,283,0.0217,-0.0035,0.2896,0.0217,0.0965,0,orlando,fl
16047,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,...,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0,apopka,fl
16849,202608,34743,"kissimmee, fl",344500.0,0.0192,-0.0431,108,0.0485,0.0909,65.0,...,-0.0397,145,0.0394,0.1154,0.3333,-0.0210,0.0404,0,kissimmee,fl
16923,202608,32828,"orlando, fl",489450.0,-0.0056,0.0136,187,0.0418,0.2897,65.0,...,-0.0550,252,0.0000,0.3194,0.3316,-0.0723,0.0212,0,orlando,fl
16974,202608,34771,"saint cloud, fl",479900.0,0.0103,0.0019,333,-0.1060,0.0342,82.0,...,-0.0195,578,-0.0602,0.1630,0.7297,0.0774,0.1863,0,saint cloud,fl
18942,202608,34769,"saint cloud, fl",319000.0,-0.0304,-0.0325,132,0.0193,0.0313,74.0,...,-0.0240,173,0.0298,0.0058,0.3258,0.0439,-0.0180,0,saint cloud,fl
20196,202608,32803,"orlando, fl",570000.0,-0.0150,0.1692,88,-0.0112,-0.1927,54.0,...,0.3269,125,0.0246,-0.1554,0.4091,0.0439,0.0054,0,orlando,fl
20590,202608,34746,"kissimmee, fl",399000.0,-0.0011,-0.0386,797,-0.0069,-0.1144,100.0,...,-0.0570,973,-0.0260,-0.0812,0.2208,-0.0222,0.0508,0,kissimmee,fl
20629,202608,34786,"windermere, fl",1089000.0,-0.0200,0.1204,233,-0.0251,-0.0567,75.0,...,0.3265,310,-0.0143,-0.0520,0.3391,0.0127,0.0030,0,windermere,fl
22377,202608,32703,"apopka, fl",405000.0,0.0095,0.0387,169,0.0563,-0.0398,66.0,...,0.0266,263,-0.0573,-0.0993,0.5740,-0.1604,-0.0681,0,apopka,fl
22590,202608,32766,"oviedo, fl",675000.0,-0.0253,0.1739,36,-0.1111,0.2414,67.0,...,0.3286,56,0.0182,0.2727,0.5556,0.1975,0.0383,0,oviedo,fl
22613,202608,32801,"orlando, fl",338000.0,-0.0721,0.0090,126,-0.0156,-0.1923,101.0,...,-0.0163,144,0.0141,-0.1628,0.1349,0.0255,0.0195,0,orlando,fl
22807,202608,32771,"sanford, fl",389500.0,0.0053,-0.0238,258,-0.0096,0.0661,69.0,...,0.0282,359,0.0406,0.1184,0.3798,0.0344,0.0658,0,sanford,fl
22980,202608,34741,"kissimmee, fl",315500.0,-0.0178,0.0177,219,-0.0331,0.0139,84.0,...,-0.0317,263,-0.0436,0.0115,0.1963,-0.0156,0.0019,0,kissimmee,fl
24400,202608,34787,"winter garden, fl",590000.0,0.0022,-0.0407,639,-0.0244,-0.0169,72.0,...,-0.0506,960,-0.0264,0.1622,0.5102,0.0048,0.2286,0,winter garden,fl
24421,202608,32808,"orlando, fl",276950.0,-0.0282,0.0257,157,0.0572,-0.0063,63.0,...,-0.0094,213,0.0441,-0.0699,0.3567,-0.0305,-0.0674,0,orlando,fl
24818,202608,32805,"orlando, fl",290000.0,0.0229,0.0841,72,0.0746,0.3585,88.0,...,-0.0243,90,0.0714,0.1688,0.2361,-0.0176,-0.1979,0,orlando,fl
25580,202608,32708,"winter springs, fl",399000.0,-0.0517,-0.0825,122,-0.0758,-0.0469,65.0,...,-0.0129,184,-0.1090,-0.0108,0.5246,-0.0474,0.0949,0,winter springs,fl
26013,202608,34747,"kissimmee, fl",449945.0,-0.0072,-0.0626,1148,-0.0013,-0.0982,106.0,...,-0.0058,1303,-0.0019,-0.0907,0.1298,-0.0059,0.0112,0,kissimmee,fl
26391,202608,32804,"orlando, fl",645000.0,0.0565,0.0223,84,-0.1250,-0.3000,72.0,...,0.0241,116,-0.1245,-0.2927,0.3571,-0.0231,0.0071,0,orlando,fl
26617,202608,32835,"orlando, fl",249950.0,-0.0002,0.0161,218,-0.1138,-0.2829,80.0,...,0.1963,273,-0.0586,-0.2178,0.2615,0.0724,0.1167,0,orlando,fl
27917,202608,32810,"orlando, fl",320000.0,0.0000,-0.0274,94,0.0000,0.1605,73.0,...,-0.0717,124,-0.0313,0.1273,0.3404,-0.0106,-0.0546,0,orlando,fl
28246,202608,34758,"kissimmee, fl",318950.0,-0.0171,-0.0618,250,0.0571,0.0204,70.0,...,-0.0300,380,0.0704,0.1176,0.5200,0.0274,0.1363,0,kissimmee,fl
28284,202608,32701,"altamonte springs, fl",194500.0,0.0237,-0.0738,132,0.0518,-0.0504,75.0,...,-0.0826,158,0.0327,-0.0706,0.1970,-0.0261,-0.0261,0,altamonte springs,fl

In [75]:
orl

,month_date_yyyymm,postal_code,zip_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,city,state
2094,202608,32807,"orlando, fl",350000.0,0.0051,-0.0141,81,0.0452,0.1096,62.0,...,0.0233,123,0.0250,0.1942,0.5185,-0.0234,0.0939,0,orlando,fl
5792,202608,34761,"ocoee, fl",438000.0,0.0368,-0.0374,137,0.0186,0.1513,68.0,...,-0.0939,215,0.0190,0.1436,0.5547,-0.0103,-0.0335,0,ocoee,fl
6641,202608,32819,"orlando, fl",525000.0,-0.0223,-0.0278,198,-0.0025,-0.1646,87.0,...,0.0056,235,-0.0208,-0.1840,0.1869,-0.0197,-0.0072,0,orlando,fl
7574,202608,32817,"orlando, fl",417500.0,-0.0430,-0.1278,53,-0.0702,-0.2090,50.0,...,-0.2889,78,-0.1086,-0.2041,0.4717,-0.1072,0.0090,1,orlando,fl
9215,202608,32806,"orlando, fl",485000.0,-0.0472,-0.0241,130,0.0788,-0.0370,72.0,...,0.0463,170,0.0366,-0.0230,0.3077,-0.0616,0.0114,0,orlando,fl
13430,202608,32827,"orlando, fl",849945.0,0.0011,0.1691,185,-0.0750,0.1212,82.0,...,0.2297,243,-0.0654,0.1302,0.3135,0.0135,0.0287,0,orlando,fl
14749,202608,32826,"orlando, fl",212000.0,-0.3737,-0.4308,64,0.1743,0.3913,42.0,...,-0.3014,89,0.0788,0.4833,0.3906,-0.1231,0.0645,1,orlando,fl
16000,202608,32832,"orlando, fl",529990.0,-0.0227,-0.0184,221,0.0208,-0.0515,72.0,...,0.0176,283,0.0217,-0.0035,0.2896,0.0217,0.0965,0,orlando,fl
16047,202608,32712,"apopka, fl",455000.0,-0.0246,-0.0712,259,0.0058,0.0792,72.0,...,-0.0921,411,0.0074,0.1743,0.5946,0.0101,0.1071,0,apopka,fl
16923,202608,32828,"orlando, fl",489450.0,-0.0056,0.0136,187,0.0418,0.2897,65.0,...,-0.0550,252,0.0000,0.3194,0.3316,-0.0723,0.0212,0,orlando,fl
20196,202608,32803,"orlando, fl",570000.0,-0.0150,0.1692,88,-0.0112,-0.1927,54.0,...,0.3269,125,0.0246,-0.1554,0.4091,0.0439,0.0054,0,orlando,fl
20629,202608,34786,"windermere, fl",1089000.0,-0.0200,0.1204,233,-0.0251,-0.0567,75.0,...,0.3265,310,-0.0143,-0.0520,0.3391,0.0127,0.0030,0,windermere,fl
22377,202608,32703,"apopka, fl",405000.0,0.0095,0.0387,169,0.0563,-0.0398,66.0,...,0.0266,263,-0.0573,-0.0993,0.5740,-0.1604,-0.0681,0,apopka,fl
22613,202608,32801,"orlando, fl",338000.0,-0.0721,0.0090,126,-0.0156,-0.1923,101.0,...,-0.0163,144,0.0141,-0.1628,0.1349,0.0255,0.0195,0,orlando,fl
24400,202608,34787,"winter garden, fl",590000.0,0.0022,-0.0407,639,-0.0244,-0.0169,72.0,...,-0.0506,960,-0.0264,0.1622,0.5102,0.0048,0.2286,0,winter garden,fl
24421,202608,32808,"orlando, fl",276950.0,-0.0282,0.0257,157,0.0572,-0.0063,63.0,...,-0.0094,213,0.0441,-0.0699,0.3567,-0.0305,-0.0674,0,orlando,fl
24818,202608,32805,"orlando, fl",290000.0,0.0229,0.0841,72,0.0746,0.3585,88.0,...,-0.0243,90,0.0714,0.1688,0.2361,-0.0176,-0.1979,0,orlando,fl
26391,202608,32804,"orlando, fl",645000.0,0.0565,0.0223,84,-0.1250,-0.3000,72.0,...,0.0241,116,-0.1245,-0.2927,0.3571,-0.0231,0.0071,0,orlando,fl
26617,202608,32835,"orlando, fl",249950.0,-0.0002,0.0161,218,-0.1138,-0.2829,80.0,...,0.1963,273,-0.0586,-0.2178,0.2615,0.0724,0.1167,0,orlando,fl
27917,202608,32810,"orlando, fl",320000.0,0.0000,-0.0274,94,0.0000,0.1605,73.0,...,-0.0717,124,-0.0313,0.1273,0.3404,-0.0106,-0.0546,0,orlando,fl